vim.pack.add {
  'https://github.com/nvim-lua/plenary.nvim',
  'https://github.com/MeanderingProgrammer/render-markdown.nvim',
  'https://github.com/saghen/blink.cmp',
  'https://github.com/folke/snacks.nvim',
  'https://github.com/sudo-tee/opencode.nvim',
}

require('render-markdown').setup {
  anti_conceal = { enabled = false },
  file_types = { 'markdown', 'opencode_output' },
}

require('opencode').setup {
  keymaps = {
    editor = {
      ['<leader>og'] = { 'toggle' },
      ['<leader>oi'] = { 'open_input' },
      ['<leader>oI'] = { 'open_input_new_session' },
      ['<leader>oo'] = { 'open_output' },
      ['<leader>ot'] = { 'toggle_focus' },
      ['<leader>oT'] = { 'timeline' },
      ['<leader>oq'] = { 'close' },
      ['<leader>os'] = { 'select_session' },
      ['<leader>oR'] = { 'rename_session' },
      ['<leader>op'] = { 'configure_provider' },
      ['<leader>oV'] = { 'configure_variant' },
      ['<leader>oy'] = { 'add_visual_selection', mode = { 'v' } },
      ['<leader>oz'] = { 'toggle_zoom' },
      ['<leader>ov'] = { 'paste_image' },
      ['<leader>od'] = { 'diff_open' },
      ['<leader>o]'] = { 'diff_next' },
      ['<leader>o['] = { 'diff_prev' },
      ['<leader>oc'] = { 'diff_close' },
      ['<leader>ora'] = { 'diff_revert_all_last_prompt' },
      ['<leader>ort'] = { 'diff_revert_this_last_prompt' },
      ['<leader>orA'] = { 'diff_revert_all' },
      ['<leader>orT'] = { 'diff_revert_this' },
      ['<leader>orr'] = { 'diff_restore_snapshot_file' },
      ['<leader>orR'] = { 'diff_restore_snapshot_all' },
      ['<leader>ox'] = { 'swap_position' },
      ['<leader>ott'] = { 'toggle_tool_output' },
      ['<leader>otr'] = { 'toggle_reasoning_output' },
      ['<leader>o/'] = { 'quick_chat', mode = { 'n', 'x' } },
    },
    input_window = {
      ['<S-cr>'] = { 'submit_input_prompt', mode = { 'n', 'i' } },
      ['<esc>'] = { 'close' },
      ['<C-c>'] = { 'cancel' },
      ['~'] = { 'mention_file', mode = 'i' },
      ['@'] = { 'mention', mode = 'i' },
      ['/'] = { 'slash_commands', mode = 'i' },
      ['#'] = { 'context_items', mode = 'i' },
      ['<M-v>'] = { 'paste_image', mode = 'i' },
      ['<C-i>'] = { 'focus_input', mode = { 'n', 'i' } },
      ['<tab>'] = { 'toggle_pane', mode = { 'n', 'i' } },
      ['<up>'] = { 'prev_prompt_history', mode = { 'n', 'i' } },
      ['<down>'] = { 'next_prompt_history', mode = { 'n', 'i' } },
      ['<M-m>'] = { 'switch_mode' },
      ['<M-r>'] = { 'cycle_variant', mode = { 'n', 'i' } },
    },
    output_window = {
      ['<esc>'] = { 'close' },
      ['<C-c>'] = { 'cancel' },
      [']]'] = { 'next_message' },
      ['[['] = { 'prev_message' },
      ['<tab>'] = { 'toggle_pane', mode = { 'n', 'i' } },
      ['i'] = { 'focus_input', 'n' },
      ['<M-r>'] = { 'cycle_variant', mode = { 'n' } },
      ['<leader>oS'] = { 'select_child_session' },
      ['<leader>oD'] = { 'debug_message' },
      ['<leader>oO'] = { 'debug_output' },
      ['<leader>ods'] = { 'debug_session' },
    },
  },
}
